name: main-pull-request

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Assigning SIMPLE_REPOSITORY_NAME
      run: echo "SIMPLE_REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Assigning SIMPLE_BRANCH_NAME
      run: |
        BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
        SIMPLE_BRANCH_NAME="${BRANCH_NAME//\//-}"
        echo "SIMPLE_BRANCH_NAME=${SIMPLE_BRANCH_NAME}" >> $GITHUB_ENV

    - name: Checkout badges branch dedicated to storing badges only
      uses: actions/checkout@v4
      with:
        ref: badges
        path: badges

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Test with coverage
      run: npm run test:coverage

    - name: What is in the badges directory before generating new badges
      run: ls -la badges

    - name: What is in the badges directory before generating new badges
      run: ls -la ${{ github.workspace }}/badges

    - name: Write to badges directory
      run: echo "Hello" >>  ${{ github.workspace }}/badges/hello.txt

    - name: What is in the badges directory before generating new badges
      run: ls -la ${{ github.workspace }}/badges
      
    - name: Generate coverage badges
      run: npx tsx ./scripts/generate-code-coverage-badge.ts
      env:
        KIT_COVERAGE_SUMMARY_BADGE_PATH: ${{ github.workspace }}/badges/${{ env.SIMPLE_BRANCH_NAME }}-coverage.svg

    - name: Upload Jest Code Coverage report
      uses: actions/upload-artifact@v4
      with:
        name: jest-coverage-report
        path: coverage/lcov-report/

    - name: Commit and Push the Badges to the badges branch
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'Push updated badges branch'
        add: '*.svg'
        pull: '--rebase --autostash'
        cwd: badges

